version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: test_my_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "19200:19200"
      - "19300:19300"


  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: test_my_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:19200
    ports:
      - "15601:15601"
    depends_on:
      - elasticsearch